### ISSUE TITLE
Mint a new 2.12.1 Release

### ISSUE THREAD

**Issue by shlomif** [thewml/website-meta-language#26]
@xtaran : please let me know if you run into any issue that should be fixed.

**Comment by xtaran** [comment]
Indeed, I planned to ask you in the next few days if you would mint a new release now that things calmed down and wml 2.12.0 is in Debian Testing now. (Actually it migrated twice already as there were a few packaging-related fixes, too. :-)

**Comment by xtaran** [comment]
Let me check if any of the patches I have in the Debian package are suitable for upstream.

**Comment by shlomif** [comment]
@xtaran : thanks! I'll wait for the debian patches check.

**Comment by xtaran** [comment]
These patches seem to be clearly suitable for upstream:

* https://salsa.debian.org/debian/wml/blob/master/debian/patches/fix-man-page-sections-and-see-also.diff
* https://salsa.debian.org/debian/wml/blob/master/debian/patches/manpage-fixes.diff

I can prepare a pull request for these two, but I can't promise it will happen today.

This one probably needs a review as it adds a feature and is from a time before I took over the maintenance of Debian's wml package:

* https://salsa.debian.org/debian/wml/blob/master/debian/patches/wml-fmt-text-txt2html.diff

It though also contains one `s/SEEALSO/SEE ALSO/` fix which should rather belong into `fix-man-page-sections-and-see-also.diff`.

Most of the remaining ones are either already fixed, taken from your commits or debian-specific.

There is one historical all-in-one patch which I first would need to examine en detail (and probably split up further) and which shouldn't keep back a new upstream release:

* https://salsa.debian.org/debian/wml/blob/master/debian/patches/wml_2.0.11ds1-0.4.diff

And then there is this one where I'm not sure if it's really needed upstream. It causes non-compiled stuff to be installed under `/usr/share/` instead of `/usr/lib/`. But this patch might not be suitable for upstream at the moment, as its tailored for building only the (non-compiled) WML part, but neither iselect, mp4h, nor slice which or what else is currently its own Debian source package: 

* https://salsa.debian.org/debian/wml/blob/master/debian/patches/datadir-for-cmake-too.diff

I might even ditch this patch again from the Debian package (or rework it) once I build all the mentioned tools from Debian's wml source package.

**Comment by shlomif** [comment]
@xtaran : thanks! I applied the first 2 patches and pushed a new tag.

**Comment by xtaran** [comment]
Thanks! Will upload it to Debian within the next one or two days. (Busy weekend ahead. :-)

**Comment by shlomif** [comment]
@xtaran : thanks! The tar.xz is available now as well. closing.
